### ISSUE TITLE
Jumping Animation Bug

### ISSUE THREAD

**Issue by JadzD2001** [Avali-Triage-Team/Avali#266]
The jumping animation when using clothing in-game shows the arms going up but the wings of the Avali don't go up. Fix?

**Comment by Jeadbe** [comment]
Avali animations are different since they are a distinctly different species. They have their own clothes which work fine, but since the game just overlays the animations, the vanilla (and most mod) clothing produces odd visual artifacts. You would need an Avali version of whatever clothes you want to wear. (this would make sense for the real world, though I understand that it might be frustrating in a game)

I would recommend taking a look at [https://trello.com/c/5y5w9zGZ/16-vanilla-clothing-changes-and-suggestions-for-clothing-to-modify](https://trello.com/c/5y5w9zGZ/16-vanilla-clothing-changes-and-suggestions-for-clothing-to-modify)
