### ISSUE TITLE
Concerning Shipdata Files

### ISSUE THREAD

**Issue by postmodernCorruption** [Avali-Triage-Team/Avali#323]
Greetings! I'm pC, fellow modder.

While working on my 99 crewsize mod for race mods, I have came across a discrepency with your data, particularly concerning your ship. In your "/universe_server.config.patch", your filepath is referencing files that are non-existant and/or misspelled, which prevents the respective ship from being used, and any other problems regarding your ship (in using/editing). Please check to be make sure the universe patch paths match the name of the files they're referencing exactly.

I hope this resolves any issue regarding your races' ship, and am looking forward to the update!

-pC, with <3

**Comment by Fevix** [comment]
https://github.com/Avali-Triage-Team/Avali/blob/master/universe_server.config.patch
"/ships/avali/avianT0.structure", "/ships/avali/avianT1.structure", "/ships/avali/avianT2.structure", "/ships/avali/avianT3.structure", "/ships/avali/avianT4.structure", "/ships/avali/avianT5.structure", "/ships/avali/avianT6.structure", "/ships/avali/avianT7.structure", "/ships/avali/avianT8.structure"

https://github.com/Avali-Triage-Team/Avali/tree/master/ships/avali
Scroll down a bit and you'll see the "avianT#" ships. 

Not a bug/error/etc.
There's an additional mod to change the patch over to avali, which allows users to change ships. (I have plans to make it so that different characters get different ships, but this'll be a bunch of work and will have to wait until RyuujinZERO finishes the rewrite)
