### ISSUE TITLE
Nanolathe bug

### ISSUE THREAD

**Issue by savron1001** [Avali-Triage-Team/Avali#329]
When I open the container tab of the nanolathe my game crashes I hope this is the file you need.
[starbound.log.zip](https://github.com/Avali-Triage-Team/Avali/files/779046/starbound.log.zip)

**Comment by Fevix** [comment]
Known issue with other mods. Have been unable to pinpoint problem mods.

**Comment by ShadowMantis** [comment]
Get the same issue. Here's my log: https://pastebin.com/M8cQeHxj
Seems that there's a recipe or other such thing missing in the nanolathe's crafting menu, specifically in the storage items tab. Which, this item is called 'avalipethouse'. Seriously, that there is the only thing that is brought up just before the crash.

Also, there's a reference to a different item that I KNOW has no association with this mod, but it'd be pointless to bring that up with the mod that it belongs to as it is no longer updated.

**Comment by Fevix** [comment]
Issue resolved. Borderlands Item Mod had some stray files that the owner was trying to use to make a pet of their own (Possibly Claptrap or a skag?) and they were using the Drone Pet mod. They decided not to in the end, and deleted most, but not all, of the files. One of the files remaining was a recipe for "avalipethouse". 

Since the base avali mod didn't HAVE an 'avalipethouse' item, the game crashes unless you have the mod that adds that item.

I've spoken to the developer of the BIM and they've removed the problem file
