### ISSUE TITLE
Game freezes and crahses when I click on the Chest Tab in the Nanolathe

### ISSUE THREAD

**Issue by FullmetalBear1** [Avali-Triage-Team/Avali#368]
I have the same issue here as Abéka in the Steam Workshop Comments. The game freezes and then crashes when I click on the Chest tab of the Nanolathe...
Starbound Log attached for your perusal, good luck and thanks for the terrific mod :)

[Starbound.log.docx](https://github.com/Avali-Triage-Team/Avali/files/1100561/Starbound.log.docx)

**Comment by Fevix** [comment]
Send me your mod pack in a .zip format please. Like, your actual mod files and everything. 

Your workshop mods can be found at `E:\Program Files (x86)\Steam\steamapps\workshop\content\211820\`

This is not an issue caused by the Avali mod, and as such I cannot directly do anything about it, but the issue has been plaguing all three of the error reporting areas for a long time and I want to get to the bottom of it.

**Comment by FullmetalBear1** [comment]
Thanks for your reply. I did have the issue before but it went away after the workshop updated the some Starbound mods a few times, but it's back now. I thought it wasn't your mod's fault. But thanks for trying to get to the bottom of this. :)

I'm trying to add the folder in .zip format but Github is being a bit moody -.-

**Comment by FullmetalBear1** [comment]
Have the file here in .zip format and Github is telling me that they don't support the file type -.-

**Comment by Fevix** [comment]
Send it via Dropbox or Google drive

**Comment by Fevix** [comment]
The issue is in the Borderlands Item Mod. I've contacted the dev and told them about it, hopefully they'll resolve it.
