### ISSUE TITLE
Fatal crash when used with Scripted SAIL and FU

### ISSUE THREAD

**Issue by Xilosc** [Avali-Triage-Team/Avali#390]
Was wondering what the reason was that this mod still includes Frackin Universe for? Graphene was changed was there anything else? Currently creates an includes loop with the other 2 mods as FU includes scripted sail so that it can continue to function and scripted sail includes Avali to support custom sails for this race. Then with Avali including FU again it creates a fatal error loop while opening Starbound.

**Comment by Fevix** [comment]
We include FU because they also contain assets from the avali mod and if we
didn't include them then our assets might be over written by their assets
and any updates we make to our assets would not send carry over to players
using both because their assets would overwrite our updated versions

On Jun 9, 2018 1:22 AM, "Remi" <notifications@github.com> wrote:

Was wondering what the reason was that this mod still includes Frackin
Universe for? Graphene was changed was there anything else? Currently
creates an includes loop with the other 2 mods as FU includes scripted sail
so that it can continue to function and scripted sail includes Avali to
support custom sails for this race. Then with Avali including FU again it
creates a fatal error loop while opening Starbound.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Avali-Triage-Team/Avali/issues/390>, or mute the thread

**Comment by Fevix** [comment]
I would be glad to remove the includes for fracking universe if they would instead use an add-on system or some other method to separate out the avali content into an add-on mod for both mods. 

In my opinion this would eliminate my need to have an includes and would therefore break the loop. The add-on mod could also simply reference the avali objects rather than including their own which would also prevent me from needing to include the add-on

**Comment by Xilosc** [comment]
I'll bring this up and possibly work on it myself this weekend if we can figure something out, for now I think Sayter has gone to sleep so I'll let you know when I have more answers! Also communicating with Scripted sail mod. Hopefully we can get everything working together properly soon!
