### ISSUE TITLE
Why remove all the comments?

### ISSUE THREAD

**Issue by AeolusDraco** [Avali-Triage-Team/Avali#392]
People need those to understand how this mod works.

**Comment by Fevix** [comment]
The comments did not mesh with TravisCI.



On Jul 23, 2018 7:11 PM, "AeolusDraco" <notifications@github.com> wrote:

People need those to understand how this mod works.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Avali-Triage-Team/Avali/issues/392>, or mute the thread

**Comment by AeolusDraco** [comment]
Why does this project need TravisCI?

**Comment by AeolusDraco** [comment]
Judging from the commits the only thing occasionally needed is a spellchecker.

**Comment by AeolusDraco** [comment]
Was that worth removing **all** the comments?

**Comment by AeolusDraco** [comment]
Every comment was put there for a reason.

**Comment by Fevix** [comment]
Most of the comments we're just stuff that was holdovers from vanilla files.

They were very very very few original Commons put in by our developers

On Jul 23, 2018 10:52 PM, "AeolusDraco" <notifications@github.com> wrote:

Every comment was put there for a reason.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Avali-Triage-Team/Avali/issues/392#issuecomment-407263752>,
or mute the thread

**Comment by AeolusDraco** [comment]
Do you know why TravisCI hates comments?

**Comment by AeolusDraco** [comment]
"Pure" JSON does not allow comments of any kind,
however there is no JSON parser which enforces this.
So you have to pick between comments or strictly following the JSON standard.

**Comment by AeolusDraco** [comment]
So
https://github.com/Avali-Triage-Team/Avali/blob/a4207fa6518ce8abe314b52e0b2a3496b012226b/species/avali.species#L220-L230
is in the vanilla game files?

**Comment by AeolusDraco** [comment]
There is no JSON parser that has problems with comments, even the official parser ignores them.
Comments are only an issue with linters because as you have stated, comments are not allowed by the JSON standard.

**Comment by AeolusDraco** [comment]
I understand how you feel about this and I'll see what I can do.

**Comment by Fevix** [comment]
Where would I put this? I see you have it in your config in TravisCI, but
how do I get it into mine?

**Comment by AeolusDraco** [comment]
Just pull one of the branches from https://github.com/AeolusDraco/Avali
here's a summary of what each branch has:
[restore-comments](https://github.com/AeolusDraco/Avali/tree/restore-comments) reverts the commits that removed comments and adds the script to travis.
[restore-comments-with-comment](https://github.com/AeolusDraco/Avali/tree/restore-comments-with-comment) will additionally add a comment to .travis.yml that explains how the new command works.
[restore-comments-and-disabled](https://github.com/AeolusDraco/Avali/tree/restore-comments-and-disabled) and [restore-comments-and-disabled-with-comment](https://github.com/AeolusDraco/Avali/tree/restore-comments-and-disabled-with-comment) will do the same as their respective bases above but will also restore *.disabled files and adds them .jsonlintignore to prevent them from breaking the build

**Comment by Fevix** [comment]
Pull request open, #394 
Please take a look at the three Reviews and address each one.

**Comment by AeolusDraco** [comment]
Where are the Reviews?

**Comment by Fevix** [comment]
Check the linked pull request

On Jul 27, 2018 6:04 PM, "AeolusDraco" <notifications@github.com> wrote:

Where are the Reviews?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/Avali-Triage-Team/Avali/issues/392#issuecomment-408550131>,
or mute the thread
