### ISSUE TITLE
Rent Collection Bug

### ISSUE THREAD

**Issue by RS-Mind** [Avali-Triage-Team/Avali#393]
While trying to collect rent from avali tenants, they die rather than give rent. Appears to be an error handler for trying to say a missing line of text.
https://pastebin.com/VpRcmdrv

**Comment by Fevix** [comment]
Lines 1277 and 1365 in your pastebin: 
1277: `Caused by: (JsonParsingException) Cannot parse json file: /dialog/arrivedhome.config`
1365: `Caused by: (JsonParsingException) Error parsing json: bad array, should be ',' or ']' at 16:5`

It's erroring because one of the mods that adds a patch to `arrivedhome.config` messed up a comma. I've gone over the avali `arrvedhome.config.patch` and there are no messed up commas in the avali file. 

ANY mod that messes up a single comma will break arrivedhome.config for all mods. Check all mods you have that have villagers that pay rent.
